export const LUMINA_OPEN_DESIGN_BASE_PATH = "/plugins/lumina-open-design";

export function renderLuminaOpenDesignUi(): string {
  return `<!doctype html>
<html lang="es" data-theme="light">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light dark">
  <title>Lumina Diseño</title>
  <style>
    :root{--bg:#f4f6f8;--panel:#fff;--panel-soft:#f8f9fb;--panel-strong:#eef1f4;--text:#17191d;--muted:#68717d;--line:#dfe3e8;--line-strong:#c9ced6;--brand:#dc3742;--brand-soft:#fff0f1;--teal:#087e73;--teal-soft:#e8f7f4;--blue:#2867d8;--blue-soft:#edf3ff;--gold:#8a6400;--gold-soft:#fff5d7;--danger:#b4232d;--shadow:0 16px 44px rgba(24,30,39,.14);font-family:Inter,"Segoe UI",Arial,sans-serif;color-scheme:light}
    html[data-theme="dark"]{--bg:#0f1114;--panel:#17191d;--panel-soft:#1b1e23;--panel-strong:#24282e;--text:#f2f4f7;--muted:#a1a9b4;--line:#30343b;--line-strong:#444a54;--brand:#ff5a64;--brand-soft:#321b20;--teal:#31c8b4;--teal-soft:#15332f;--blue:#78a5ff;--blue-soft:#192945;--gold:#f2c65f;--gold-soft:#302817;--danger:#ff6d75;--shadow:0 18px 50px rgba(0,0,0,.34);color-scheme:dark}
    *{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden;background:var(--bg);color:var(--text)}button,input,select,textarea{font:inherit;letter-spacing:0}button{cursor:pointer}svg{display:block}.hidden{display:none!important}
    .app{height:100%;display:grid;grid-template-rows:62px minmax(0,1fr)}
    .topbar{display:flex;align-items:center;gap:16px;padding:0 16px;border-bottom:1px solid var(--line);background:var(--panel);min-width:0}
    .brand{display:flex;align-items:center;gap:10px;min-width:240px}.mascot{width:36px;height:36px;flex:0 0 auto}.brand-copy{min-width:0}.brand-copy strong{display:block;font-size:14px}.brand-copy span{display:block;margin-top:2px;color:var(--muted);font-size:10px;white-space:nowrap}
    .connection-strip{display:flex;align-items:center;gap:8px;min-width:0}.status-pill,.model-pill{height:30px;display:flex;align-items:center;gap:7px;padding:0 10px;border:1px solid var(--line);border-radius:6px;background:var(--panel-soft);font-size:11px;white-space:nowrap}.status-pill{color:var(--muted)}.model-pill{color:var(--text)}.dot{width:7px;height:7px;border-radius:50%;background:#929aa4;flex:0 0 auto}.dot.ok{background:#15a887}.dot.bad{background:var(--brand)}.dot.warn{background:#d49a14}
    .top-actions{margin-left:auto;display:flex;align-items:center;gap:7px}.icon-btn,.text-btn{height:34px;border:1px solid var(--line);border-radius:6px;background:var(--panel);color:var(--text);display:inline-flex;align-items:center;justify-content:center;gap:7px;font-weight:650;font-size:11px}.icon-btn{width:34px;padding:0}.text-btn{padding:0 11px}.icon-btn:hover,.text-btn:hover{border-color:var(--line-strong);background:var(--panel-strong)}.icon-btn:focus-visible,.text-btn:focus-visible,.project:focus-visible,.tab:focus-visible,.view-btn:focus-visible{outline:2px solid var(--blue);outline-offset:2px}.icon{width:16px;height:16px;stroke:currentColor;fill:none;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.primary{background:var(--brand);border-color:var(--brand);color:#fff}.primary:hover{background:#c92e38;border-color:#c92e38}.primary:disabled{opacity:.48;cursor:not-allowed}
    .workspace{min-height:0;display:grid;grid-template-columns:268px minmax(500px,1fr) minmax(340px,38%)}
    .sidebar,.preview{min-height:0;background:var(--panel)}.sidebar{border-right:1px solid var(--line);display:grid;grid-template-rows:auto auto minmax(0,1fr) auto}.preview{border-left:1px solid var(--line);display:grid;grid-template-rows:48px minmax(0,1fr) 38px}
    .side-head{height:49px;display:flex;align-items:center;padding:0 12px;border-bottom:1px solid var(--line)}.side-head strong{font-size:12px}.side-head .count{margin-left:6px;color:var(--muted);font-size:11px}.side-head .icon-btn{margin-left:auto;width:30px;height:30px}
    .search-wrap{padding:10px 10px 7px}.search{height:34px;position:relative}.search svg{position:absolute;left:10px;top:9px;color:var(--muted)}.search input{width:100%;height:34px;border:1px solid var(--line);border-radius:6px;background:var(--panel-soft);color:var(--text);padding:0 10px 0 32px;outline:none;font-size:11px}.search input:focus{border-color:var(--blue);box-shadow:0 0 0 3px color-mix(in srgb,var(--blue) 14%,transparent)}
    .project-list{padding:3px 7px 10px;overflow:auto}.project{width:100%;display:grid;grid-template-columns:30px minmax(0,1fr) auto;align-items:center;gap:8px;text-align:left;border:0;background:transparent;color:var(--text);padding:8px;border-radius:6px;min-height:50px}.project:hover{background:var(--panel-soft)}.project.active{background:var(--brand-soft);box-shadow:inset 3px 0 var(--brand)}.project-mark{width:30px;height:30px;border-radius:6px;background:var(--panel-strong);color:var(--muted);display:grid;place-items:center;font-size:10px;font-weight:800}.project.active .project-mark{background:var(--brand);color:#fff}.project-copy{min-width:0}.project strong{display:block;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.project small{display:block;margin-top:4px;color:var(--muted);font-size:9px}.status-tick{width:6px;height:6px;border-radius:50%;background:#a1a8b0}.status-tick.active{background:var(--teal)}.status-tick.failed{background:var(--brand)}.empty{padding:34px 18px;color:var(--muted);font-size:11px;text-align:center;line-height:1.5}
    .system-panel{border-top:1px solid var(--line);padding:10px}.system-row{display:grid;grid-template-columns:28px minmax(0,1fr) auto;gap:8px;align-items:center}.system-icon{width:28px;height:28px;border-radius:6px;background:var(--teal-soft);color:var(--teal);display:grid;place-items:center}.system-row strong{font-size:10px}.system-row small{display:block;color:var(--muted);font-size:9px;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sync-btn{border:0;background:transparent;color:var(--blue);font-size:9px;font-weight:700;padding:5px}.sync-btn:hover{text-decoration:underline}
    .main{min-height:0;display:grid;grid-template-rows:auto 45px minmax(0,1fr);background:var(--bg)}
    .project-header{padding:18px 22px 14px;background:var(--panel);border-bottom:1px solid var(--line);display:flex;align-items:flex-start;gap:16px}.project-heading{min-width:0}.eyebrow{color:var(--teal);font-size:9px;font-weight:800;text-transform:uppercase}.project-heading h1{font-size:22px;line-height:1.15;margin:6px 0 5px;letter-spacing:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.project-heading p{margin:0;color:var(--muted);font-size:11px}.header-meta{margin-left:auto;display:flex;gap:8px}.meta-block{min-width:76px;border-left:1px solid var(--line);padding-left:10px}.meta-block span{display:block;color:var(--muted);font-size:8px;text-transform:uppercase}.meta-block strong{display:block;margin-top:4px;font-size:10px;white-space:nowrap}
    .tabs{display:flex;align-items:end;gap:2px;padding:0 18px;background:var(--panel);border-bottom:1px solid var(--line)}.tab{height:45px;border:0;border-bottom:2px solid transparent;background:transparent;color:var(--muted);padding:0 12px;font-size:11px;font-weight:650}.tab:hover{color:var(--text)}.tab.active{color:var(--text);border-bottom-color:var(--brand)}
    .content{min-height:0;overflow:auto;padding:20px 22px 28px}.view{max-width:920px;margin:0 auto}.section{padding:0 0 20px;margin:0 0 20px;border-bottom:1px solid var(--line)}.section:last-child{border-bottom:0;margin-bottom:0}.section-title{display:flex;align-items:flex-start;gap:14px;margin-bottom:13px}.step{width:24px;height:24px;border:1px solid var(--line-strong);border-radius:6px;display:grid;place-items:center;color:var(--muted);font-size:9px;font-weight:800;flex:0 0 auto}.section-title h2{font-size:13px;margin:1px 0 3px}.section-title p{font-size:10px;color:var(--muted);margin:0;line-height:1.45}
    .row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field{display:grid;gap:6px}.field label{color:var(--muted);font-size:9px;font-weight:700}.field input,.field select,.field textarea{width:100%;border:1px solid var(--line);border-radius:6px;background:var(--panel);color:var(--text);padding:9px 10px;outline:none;font-size:11px}.field input,.field select{height:38px}.field textarea{min-height:170px;resize:vertical;line-height:1.55}.field input:focus,.field select:focus,.field textarea:focus{border-color:var(--blue);box-shadow:0 0 0 3px color-mix(in srgb,var(--blue) 14%,transparent)}
    .format-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.format-btn{height:58px;border:1px solid var(--line);border-radius:6px;background:var(--panel);color:var(--muted);display:grid;place-items:center;align-content:center;gap:5px;font-size:9px}.format-btn:hover{border-color:var(--line-strong);color:var(--text)}.format-btn.active{border-color:var(--brand);background:var(--brand-soft);color:var(--brand)}.format-btn svg{width:17px;height:17px}
    .prompt-tools{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px}.prompt-chip{height:28px;border:1px solid var(--line);border-radius:6px;background:var(--panel);color:var(--muted);padding:0 9px;font-size:9px}.prompt-chip:hover{border-color:var(--blue);color:var(--blue)}
    .advanced{margin-top:12px}.advanced summary{cursor:pointer;color:var(--muted);font-size:10px;font-weight:650;list-style:none;display:flex;align-items:center;gap:6px}.advanced summary::-webkit-details-marker{display:none}.advanced[open] summary{color:var(--text)}.advanced .row{margin-top:11px}
    .action-bar{position:sticky;bottom:-28px;margin:20px -22px -28px;padding:12px 22px;border-top:1px solid var(--line);background:color-mix(in srgb,var(--bg) 94%,transparent);backdrop-filter:blur(10px);display:flex;align-items:center;gap:8px;z-index:2}.action-bar .text-btn{height:38px}.run-hint{margin-left:auto;color:var(--muted);font-size:9px;text-align:right;max-width:300px;line-height:1.4}
    .timeline{display:grid}.event{display:grid;grid-template-columns:18px minmax(0,1fr) auto;gap:10px;position:relative;padding:0 0 18px}.event:before{content:"";position:absolute;left:8px;top:18px;bottom:0;width:1px;background:var(--line)}.event:last-child:before{display:none}.event-dot{width:17px;height:17px;border:4px solid var(--bg);border-radius:50%;background:var(--teal);z-index:1}.event.failed .event-dot{background:var(--brand)}.event strong{font-size:11px}.event p{margin:4px 0 0;color:var(--muted);font-size:10px}.event time{color:var(--muted);font-size:9px}
    .file-table{border-top:1px solid var(--line)}.file-row{min-height:46px;display:grid;grid-template-columns:30px minmax(0,1fr) 70px auto;align-items:center;gap:10px;border-bottom:1px solid var(--line);font-size:10px}.file-icon{width:28px;height:28px;border-radius:6px;background:var(--blue-soft);color:var(--blue);display:grid;place-items:center;font-size:8px;font-weight:800}.file-name{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:650}.file-type{color:var(--muted);font-size:9px}.file-open{border:0;background:transparent;color:var(--blue);font-size:9px;font-weight:700}
    .preview-head{display:flex;align-items:center;gap:8px;padding:0 10px;border-bottom:1px solid var(--line)}.preview-head strong{font-size:10px}.viewport-control{margin-left:auto;display:flex;align-items:center;padding:2px;border:1px solid var(--line);border-radius:6px;background:var(--panel-soft)}.view-btn{width:28px;height:26px;border:0;border-radius:4px;background:transparent;color:var(--muted);display:grid;place-items:center}.view-btn:hover{color:var(--text)}.view-btn.active{background:var(--panel);color:var(--blue);box-shadow:0 1px 3px rgba(0,0,0,.08)}.preview-head .icon-btn{width:30px;height:30px}
    .preview-stage{position:relative;min-height:0;overflow:auto;display:grid;place-items:center;padding:18px;background:repeating-conic-gradient(var(--panel-strong) 0 25%,var(--panel-soft) 0 50%) 50%/18px 18px}.device{width:100%;height:100%;min-height:300px;background:#fff;box-shadow:0 8px 24px rgba(0,0,0,.13);transition:width .18s ease,height .18s ease}.device.tablet{width:min(768px,100%);height:92%}.device.mobile{width:min(390px,100%);height:88%}.device iframe{width:100%;height:100%;border:0;background:#fff}.preview-empty{position:absolute;inset:18px;display:grid;place-items:center;background:var(--panel);color:var(--muted);text-align:center;padding:26px;font-size:11px;line-height:1.5}.preview-empty svg{width:32px;height:32px;margin:0 auto 10px;color:var(--line-strong)}
    .filebar{display:flex;align-items:center;gap:8px;padding:0 10px;border-top:1px solid var(--line);background:var(--panel)}.filebar select{min-width:0;flex:1;border:0;background:transparent;color:var(--text);font-size:9px;outline:none}.filebar span{color:var(--muted);font-size:8px}
    .toast{position:fixed;right:18px;bottom:18px;max-width:380px;padding:11px 14px;border-radius:6px;background:#171a1f;color:#fff;box-shadow:var(--shadow);font-size:11px;z-index:20}.toast.error{background:var(--danger)}
    .mobile-only{display:none}.preview.open{display:grid}
    @media(max-width:1180px){.workspace{grid-template-columns:250px minmax(0,1fr)}.preview{position:fixed;z-index:12;inset:62px 0 0 250px;display:none;box-shadow:var(--shadow)}.mobile-only{display:inline-flex}.format-grid{grid-template-columns:repeat(3,1fr)}}
    @media(max-width:760px){.brand{min-width:0}.brand-copy span,.connection-strip .status-pill,.header-meta,.top-actions .desktop-only{display:none}.workspace{grid-template-columns:1fr}.sidebar{position:fixed;z-index:14;inset:62px auto 0 0;width:min(300px,88vw);display:none;box-shadow:var(--shadow)}.sidebar.open{display:grid}.main{grid-column:1}.preview{inset:62px 0 0}.project-header{padding:15px 16px}.project-heading h1{font-size:18px}.content{padding:18px 15px 24px}.row{grid-template-columns:1fr}.format-grid{grid-template-columns:repeat(3,1fr)}.action-bar{margin:18px -15px -24px;padding:10px 15px}.run-hint{display:none}.topbar{padding:0 10px}.model-pill{font-size:9px}.mobile-projects{display:inline-flex}}
  </style>
</head>
<body>
  <div class="app">
    <header class="topbar">
      <button id="mobileProjects" class="icon-btn mobile-only mobile-projects" type="button" title="Proyectos" aria-label="Proyectos"><svg class="icon" viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16"/></svg></button>
      <div class="brand">
        <svg class="mascot" viewBox="0 0 64 64" role="img" aria-label="Lumina"><path d="M22 13 14 5M42 13l8-8" fill="none" stroke="#ff575f" stroke-width="5" stroke-linecap="round"/><circle cx="32" cy="34" r="25" fill="#e6323b"/><ellipse cx="10" cy="36" rx="7" ry="10" fill="#e6323b"/><ellipse cx="54" cy="36" rx="7" ry="10" fill="#e6323b"/><circle cx="24" cy="29" r="6" fill="#10151d"/><circle cx="40" cy="29" r="6" fill="#10151d"/><circle cx="24" cy="29" r="2.5" fill="#16d4bd"/><circle cx="40" cy="29" r="2.5" fill="#16d4bd"/><path d="M25 39c2 8 12 8 14 0Z" fill="#10151d"/></svg>
        <div class="brand-copy"><strong>Lumina Diseño</strong><span>Workspace visual conectado a OpenDesign</span></div>
      </div>
      <div class="connection-strip">
        <div class="status-pill"><span id="statusDot" class="dot"></span><span id="statusText">Conectando...</span></div>
        <div class="model-pill"><svg class="icon" viewBox="0 0 24 24"><path d="M12 3a5 5 0 0 0-5 5v1a4 4 0 0 0-2 3.5A4.5 4.5 0 0 0 9.5 17H10v4h4v-4h.5a4.5 4.5 0 0 0 4.5-4.5A4 4 0 0 0 17 9V8a5 5 0 0 0-5-5Z"/><path d="M9 10h.01M15 10h.01M9.5 14h5"/></svg><span>GLM 5.2 · OpenClaw</span></div>
      </div>
      <div class="top-actions">
        <button id="previewToggle" class="icon-btn mobile-only" type="button" title="Vista previa" aria-label="Vista previa"><svg class="icon" viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="14" rx="2"/><path d="M8 21h8M12 18v3"/></svg></button>
        <button id="themeButton" class="icon-btn" type="button" title="Cambiar tema" aria-label="Cambiar tema"><svg class="icon" viewBox="0 0 24 24"><path d="M12 3a6 6 0 1 0 9 9 9 9 0 1 1-9-9Z"/></svg></button>
        <button id="studioButton" class="text-btn desktop-only" type="button"><svg class="icon" viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M8 21V8h13M8 8H3"/></svg>Abrir Studio</button>
      </div>
    </header>
    <div class="workspace">
      <aside id="sidebar" class="sidebar">
        <div class="side-head"><strong>Proyectos</strong><span id="projectCount" class="count">0</span><button id="newProjectSide" class="icon-btn" type="button" title="Proyecto nuevo" aria-label="Proyecto nuevo"><svg class="icon" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg></button></div>
        <div class="search-wrap"><div class="search"><svg class="icon" viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input id="projectSearch" type="search" placeholder="Buscar proyectos" aria-label="Buscar proyectos"></div></div>
        <div id="projectList" class="project-list"></div>
        <div class="system-panel"><div class="system-row"><div class="system-icon"><svg class="icon" viewBox="0 0 24 24"><path d="M8 12h8M12 8v8"/><circle cx="12" cy="12" r="9"/></svg></div><div><strong id="integrationTitle">Enlace con OpenClaw</strong><small id="integrationDetail">Verificando agente del Studio</small></div><button id="syncButton" class="sync-btn" type="button">Sincronizar</button></div></div>
      </aside>
      <main class="main">
        <div class="project-header">
          <div class="project-heading"><div class="eyebrow" id="projectEyebrow">Nuevo proyecto</div><h1 id="pageTitle">Diseña con Lumina</h1><p id="pageSubtitle">Crea un artefacto persistente con el modelo activo de OpenClaw.</p></div>
          <div class="header-meta"><div class="meta-block"><span>Motor</span><strong id="runtimeSource">Conectando</strong></div><div class="meta-block"><span>Archivos</span><strong id="fileMetric">0</strong></div><div class="meta-block"><span>Actividad</span><strong id="activityMetric">0</strong></div></div>
        </div>
        <nav class="tabs" aria-label="Vistas del proyecto"><button class="tab active" data-view="create" type="button">Crear</button><button class="tab" data-view="activity" type="button">Actividad</button><button class="tab" data-view="files" type="button">Archivos</button></nav>
        <div class="content">
          <div id="createView" class="view">
            <form id="designForm">
              <section class="section"><div class="section-title"><span class="step">01</span><div><h2>Dirección del proyecto</h2><p>Define la pieza y el contexto de trabajo.</p></div></div><div class="row"><div class="field"><label for="name">Nombre del proyecto</label><input id="name" maxlength="90" placeholder="Ej. Centro operativo de memoria" required></div><div class="field"><label for="designSystem">Sistema de diseño</label><select id="designSystem"><option value="">Selección automática</option></select></div></div></section>
              <section class="section"><div class="section-title"><span class="step">02</span><div><h2>Formato</h2><p>Selecciona la estructura principal del resultado.</p></div></div><input id="kind" type="hidden" value="web"><div class="format-grid"><button class="format-btn active" data-kind="web" type="button"><svg class="icon" viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18"/></svg>Web</button><button class="format-btn" data-kind="dashboard" type="button"><svg class="icon" viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="9" rx="1"/><rect x="14" y="3" width="7" height="5" rx="1"/><rect x="14" y="12" width="7" height="9" rx="1"/><rect x="3" y="16" width="7" height="5" rx="1"/></svg>Dashboard</button><button class="format-btn" data-kind="mobile" type="button"><svg class="icon" viewBox="0 0 24 24"><rect x="7" y="2" width="10" height="20" rx="2"/><path d="M11 18h2"/></svg>App móvil</button><button class="format-btn" data-kind="deck" type="button"><svg class="icon" viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="14" rx="2"/><path d="M8 22l4-4 4 4"/></svg>Presentación</button><button class="format-btn" data-kind="poster" type="button"><svg class="icon" viewBox="0 0 24 24"><rect x="5" y="2" width="14" height="20" rx="2"/><path d="M8 6h8M8 10h5M8 17l3-3 2 2 3-4"/></svg>Póster</button><button class="format-btn" data-kind="brand" type="button"><svg class="icon" viewBox="0 0 24 24"><path d="M12 3 4 7v10l8 4 8-4V7Z"/><path d="m4 7 8 4 8-4M12 11v10"/></svg>Marca</button></div></section>
              <section class="section"><div class="section-title"><span class="step">03</span><div><h2>Solicitud para Lumina</h2><p>Describe objetivo, audiencia, contenido, estados y comportamiento.</p></div></div><div class="field"><label for="brief">Brief</label><textarea id="brief" maxlength="8000" placeholder="Describe con detalle lo que quieres construir..." required></textarea></div><div class="prompt-tools"><button class="prompt-chip" data-prompt="Incluye estados vacío, carga, error y éxito. " type="button">Estados completos</button><button class="prompt-chip" data-prompt="Prioriza accesibilidad, navegación por teclado y contraste AA. " type="button">Accesibilidad</button><button class="prompt-chip" data-prompt="Diseña versiones desktop, tablet y móvil. " type="button">Responsive</button><button class="prompt-chip" data-prompt="Usa contenido realista en español, sin placeholders. " type="button">Contenido real</button><button class="prompt-chip" data-prompt="Incluye interacciones y microestados funcionales. " type="button">Interacciones</button></div><details class="advanced"><summary><svg class="icon" viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg>Configuración avanzada</summary><div class="row"><div class="field"><label for="skill">Skill de diseño</label><select id="skill"><option value="">Selección automática</option></select></div><div class="field"><label for="quality">Prioridad</label><select id="quality"><option value="balanced">Equilibrada</option><option value="fidelity">Fidelidad visual</option><option value="speed">Iteración rápida</option><option value="accessibility">Accesibilidad</option></select></div></div></details></section>
              <div class="action-bar"><button id="submitButton" class="text-btn primary" type="submit"><svg class="icon" viewBox="0 0 24 24"><path d="m5 12 14-7-4 14-3-6Z"/><path d="M12 13 19 5"/></svg>Crear con Lumina</button><button id="newButton" class="text-btn" type="button">Limpiar</button><span id="runHint" class="run-hint">El resultado aparecerá en la mesa de vista previa.</span></div>
            </form>
          </div>
          <div id="activityView" class="view hidden"><div id="timeline" class="timeline"></div></div>
          <div id="filesView" class="view hidden"><div id="fileTable" class="file-table"></div></div>
        </div>
      </main>
      <section id="previewPanel" class="preview">
        <div class="preview-head"><strong>Vista previa</strong><div class="viewport-control"><button class="view-btn active" data-viewport="desktop" type="button" title="Escritorio" aria-label="Escritorio"><svg class="icon" viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="14" rx="2"/><path d="M8 21h8M12 18v3"/></svg></button><button class="view-btn" data-viewport="tablet" type="button" title="Tablet" aria-label="Tablet"><svg class="icon" viewBox="0 0 24 24"><rect x="5" y="2" width="14" height="20" rx="2"/><path d="M11 18h2"/></svg></button><button class="view-btn" data-viewport="mobile" type="button" title="Móvil" aria-label="Móvil"><svg class="icon" viewBox="0 0 24 24"><rect x="7" y="2" width="10" height="20" rx="2"/><path d="M11 18h2"/></svg></button></div><button id="refreshPreview" class="icon-btn" type="button" title="Actualizar" aria-label="Actualizar"><svg class="icon" viewBox="0 0 24 24"><path d="M20 6v5h-5M4 18v-5h5"/><path d="M18.5 9A7 7 0 0 0 6 6.5L4 9M5.5 15A7 7 0 0 0 18 17.5l2-2.5"/></svg></button><button id="openPreview" class="icon-btn" type="button" title="Abrir vista previa" aria-label="Abrir vista previa"><svg class="icon" viewBox="0 0 24 24"><path d="M14 3h7v7M10 14 21 3"/><path d="M21 14v5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5"/></svg></button><button id="closePreview" class="icon-btn mobile-only" type="button" title="Cerrar" aria-label="Cerrar"><svg class="icon" viewBox="0 0 24 24"><path d="M18 6 6 18M6 6l12 12"/></svg></button></div>
        <div class="preview-stage"><div id="device" class="device"><iframe id="previewFrame" class="hidden" title="Vista previa del diseño" sandbox="allow-scripts allow-forms"></iframe></div><div id="previewEmpty" class="preview-empty"><div><svg class="icon" viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M8 14h3M8 17h8"/></svg>Selecciona un proyecto o crea un diseño para revisar sus artefactos.</div></div></div>
        <div class="filebar"><select id="fileSelect" aria-label="Archivo de vista previa"><option value="">Sin artefactos</option></select><span id="previewMeta">—</span></div>
      </section>
    </div>
  </div>
  <div id="toast" class="toast hidden" role="status"></div>
  <script>
    const BASE=${JSON.stringify(LUMINA_OPEN_DESIGN_BASE_PATH)};
    const state={projects:[],selected:null,files:[],conversations:[],poll:null,status:null,view:'create',search:''};
    const hostPending=new Map();
    const $=(id)=>document.getElementById(id);
    const toast=(message,error=false)=>{const el=$('toast');el.textContent=message;el.className='toast'+(error?' error':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast hidden',4200)};
    async function api(path,options){const response=await fetch(BASE+path,{headers:{'content-type':'application/json'},...options});const raw=await response.text();let body={};try{body=raw?JSON.parse(raw):{}}catch{body={error:raw}}if(!response.ok)throw new Error(body.error||body.message||('Error '+response.status));return body}
    function host(action,payload={}){return new Promise((resolve,reject)=>{const id=crypto.randomUUID();const timer=setTimeout(()=>{hostPending.delete(id);reject(new Error('La acción del Gateway excedió el tiempo de espera.'))},35000);hostPending.set(id,{resolve,reject,timer});parent.postMessage({type:'lumina-open-design:request',id,action,payload},location.origin)})}
    window.addEventListener('message',(event)=>{if(event.source!==parent||event.origin!==location.origin)return;const data=event.data;if(!data||data.type!=='lumina-open-design:response'||typeof data.id!=='string')return;const pending=hostPending.get(data.id);if(!pending)return;clearTimeout(pending.timer);hostPending.delete(data.id);if(data.ok)pending.resolve(data.result);else pending.reject(new Error(data.error||'La acción del Gateway falló.'))});
    function integrationText(integration){if(integration&&integration.connected)return['Studio conectado','openclaw/default · sin saldo OpenDesign'];if(integration&&integration.configured)return['Conexión pendiente',integration.error||'Reinicia el Gateway'];return['Enlace con OpenClaw',integration&&integration.error||'Verificando agente del Studio']}
    function setStatus(status){state.status=status;$('statusDot').className='dot '+(status.ready?'ok':'bad');$('statusText').textContent=status.ready?('OpenDesign '+(status.version||'activo')):(status.installed?'OpenDesign sin conexión':'OpenDesign no instalado');$('runtimeSource').textContent=status.source==='studio'?'Studio nativo':status.source==='managed'?'Daemon compartido':'Daemon local';$('submitButton').disabled=!status.ready;const labels=integrationText(status.integration);$('integrationTitle').textContent=labels[0];$('integrationDetail').textContent=labels[1]}
    async function loadStatus(){try{setStatus(await api('/api/status'))}catch(error){setStatus({ready:false,installed:true,source:'configured',integration:{}});toast(error.message,true)}}
    function appendOptions(select,items,label){const fragment=document.createDocumentFragment();for(const item of items){const option=document.createElement('option');option.value=item.id;option.textContent=String(item[label]||item.name||item.id);fragment.append(option)}select.append(fragment)}
    async function loadCatalog(){try{const data=await api('/api/catalog');appendOptions($('skill'),data.skills||[],'name');appendOptions($('designSystem'),data.designSystems||[],'name')}catch(error){toast(error.message,true)}}
    function projectStatus(project){return project.status&&project.status.value?String(project.status.value):'listo'}
    function statusClass(value){return /fail|error/i.test(value)?'failed':/active|running|progress|started/i.test(value)?'active':''}
    function initials(name){return String(name||'P').split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase()}
    function renderProjects(){const root=$('projectList');root.replaceChildren();const query=state.search.toLowerCase();const projects=state.projects.filter(project=>!query||String(project.name).toLowerCase().includes(query));$('projectCount').textContent=state.projects.length;if(!projects.length){const empty=document.createElement('div');empty.className='empty';empty.textContent=state.projects.length?'No hay coincidencias.':'Aún no hay proyectos locales.';root.append(empty);return}for(const project of projects){const button=document.createElement('button');button.type='button';button.className='project'+(state.selected===project.id?' active':'');const mark=document.createElement('span');mark.className='project-mark';mark.textContent=initials(project.name);const copy=document.createElement('span');copy.className='project-copy';const strong=document.createElement('strong');strong.textContent=project.name;const small=document.createElement('small');const status=projectStatus(project);small.textContent=status.replaceAll('_',' ');copy.append(strong,small);const tick=document.createElement('span');tick.className='status-tick '+statusClass(status);button.append(mark,copy,tick);button.addEventListener('click',()=>selectProject(project.id));root.append(button)}}
    async function loadProjects(selectNewest=false){const data=await api('/api/projects');state.projects=data.projects||[];if(selectNewest&&state.projects.length)state.selected=state.projects.toSorted((a,b)=>(b.createdAt||0)-(a.createdAt||0))[0].id;if(state.selected&&!state.projects.some(project=>project.id===state.selected))state.selected=null;renderProjects();if(state.selected)await Promise.all([loadProjectFiles(),loadConversations()])}
    async function selectProject(id){state.selected=id;renderProjects();const project=state.projects.find(item=>item.id===id);$('projectEyebrow').textContent='Proyecto OpenDesign';$('pageTitle').textContent=project?project.name:'Diseña con Lumina';$('pageSubtitle').textContent='Artefactos persistentes y editables, compartidos con OpenDesign Studio.';$('name').value=project?project.name:'';await Promise.all([loadProjectFiles(),loadConversations()]);$('previewPanel').classList.add('open');$('sidebar').classList.remove('open')}
    function encodedPath(value){return value.split('/').map(encodeURIComponent).join('/')}
    function showPreview(filePath){const frame=$('previewFrame');if(!state.selected||!filePath){frame.classList.add('hidden');$('previewEmpty').classList.remove('hidden');$('previewMeta').textContent='—';return}frame.src=BASE+'/preview/'+encodeURIComponent(state.selected)+'/'+encodedPath(filePath);frame.classList.remove('hidden');$('previewEmpty').classList.add('hidden');$('previewMeta').textContent=filePath.split('.').pop().toUpperCase()}
    function filePath(file){return file.path||file.name||''}
    function renderFiles(){const root=$('fileTable');root.replaceChildren();$('fileMetric').textContent=state.files.length;if(!state.files.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='Este proyecto todavía no tiene artefactos.';root.append(empty);return}for(const file of state.files){const path=filePath(file);const row=document.createElement('div');row.className='file-row';const icon=document.createElement('span');icon.className='file-icon';icon.textContent=(path.split('.').pop()||'FILE').slice(0,4).toUpperCase();const name=document.createElement('span');name.className='file-name';name.textContent=path;const type=document.createElement('span');type.className='file-type';type.textContent=file.mime||file.contentType||'artefacto';const open=document.createElement('button');open.type='button';open.className='file-open';open.textContent='Previsualizar';open.addEventListener('click',()=>{$('fileSelect').value=path;showPreview(path);$('previewPanel').classList.add('open')});row.append(icon,name,type,open);root.append(row)}}
    async function loadProjectFiles(){if(!state.selected)return;try{const data=await api('/api/projects/'+encodeURIComponent(state.selected)+'/files');state.files=data.files||[];const previewable=state.files.filter(file=>/[.](html?|svg|md)$/i.test(filePath(file)));const select=$('fileSelect');select.replaceChildren();if(!previewable.length){const option=document.createElement('option');option.value='';option.textContent='Sin artefactos previsualizables';select.append(option);showPreview('')}else{for(const file of previewable){const option=document.createElement('option');option.value=filePath(file);option.textContent=filePath(file);select.append(option)}const preferred=previewable.find(file=>/index[.]html$/i.test(filePath(file)))||previewable[0];select.value=filePath(preferred);showPreview(select.value)}renderFiles()}catch(error){toast(error.message,true)}}
    function relativeTime(timestamp){if(!timestamp)return'—';const minutes=Math.max(0,Math.floor((Date.now()-timestamp)/60000));if(minutes<1)return'ahora';if(minutes<60)return'hace '+minutes+' min';const hours=Math.floor(minutes/60);if(hours<24)return'hace '+hours+' h';return new Date(timestamp).toLocaleDateString('es')}
    function renderTimeline(){const root=$('timeline');root.replaceChildren();$('activityMetric').textContent=state.conversations.length;if(!state.conversations.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='La actividad del proyecto aparecerá aquí.';root.append(empty);return}for(const conversation of state.conversations.toSorted((a,b)=>(b.updatedAt||0)-(a.updatedAt||0))){const event=document.createElement('div');const run=conversation.latestRun||{};event.className='event '+statusClass(run.status||'');const dot=document.createElement('span');dot.className='event-dot';const copy=document.createElement('div');const title=document.createElement('strong');title.textContent=conversation.title||'Conversación de diseño';const detail=document.createElement('p');detail.textContent=(run.status||'registrada')+' · '+(conversation.messageCount||0)+' mensajes';copy.append(title,detail);const time=document.createElement('time');time.textContent=relativeTime(conversation.updatedAt);event.append(dot,copy,time);root.append(event)}}
    async function loadConversations(){if(!state.selected)return;try{const data=await api('/api/projects/'+encodeURIComponent(state.selected)+'/conversations');state.conversations=data.conversations||[];renderTimeline()}catch{state.conversations=[];renderTimeline()}}
    function resetProject(){state.selected=null;state.files=[];state.conversations=[];$('name').value='';$('brief').value='';$('projectEyebrow').textContent='Nuevo proyecto';$('pageTitle').textContent='Diseña con Lumina';$('pageSubtitle').textContent='Crea un artefacto persistente con el modelo activo de OpenClaw.';$('fileMetric').textContent='0';$('activityMetric').textContent='0';renderProjects();renderFiles();renderTimeline();showPreview('')}
    function startPolling(){clearInterval(state.poll);let ticks=0;state.poll=setInterval(async()=>{ticks++;await loadProjects();if(ticks>=60)clearInterval(state.poll)},3000)}
    function switchView(name){state.view=name;document.querySelectorAll('.tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.view===name));['create','activity','files'].forEach(view=>$(view+'View').classList.toggle('hidden',view!==name))}
    $('designForm').addEventListener('submit',async(event)=>{event.preventDefault();const brief=$('brief').value.trim();const name=$('name').value.trim();if(!brief||!name)return;const button=$('submitButton');button.disabled=true;button.lastChild.textContent=' Iniciando...';try{const quality=$('quality').value;const enriched=brief+'\\n\\nPrioridad de ejecución: '+quality+'.';const result=await host('create',{projectId:state.selected||undefined,name,brief:enriched,kind:$('kind').value,designSystem:$('designSystem').value||undefined,skill:$('skill').value||undefined});state.selected=result.projectId;$('runHint').textContent='Lumina está trabajando en '+result.projectId+'.';toast('Solicitud enviada a Lumina.');await loadProjects();startPolling()}catch(error){toast(error.message,true)}finally{button.disabled=false;button.lastChild.textContent=' Crear con Lumina'}});
    document.querySelectorAll('.format-btn').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.format-btn').forEach(item=>item.classList.remove('active'));button.classList.add('active');$('kind').value=button.dataset.kind}));
    document.querySelectorAll('.prompt-chip').forEach(button=>button.addEventListener('click',()=>{$('brief').value=($('brief').value.trim()+' '+button.dataset.prompt).trim();$('brief').focus()}));
    document.querySelectorAll('.tab').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view)));
    document.querySelectorAll('.view-btn').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.view-btn').forEach(item=>item.classList.remove('active'));button.classList.add('active');$('device').className='device '+(button.dataset.viewport==='desktop'?'':button.dataset.viewport)}));
    $('newButton').addEventListener('click',resetProject);$('newProjectSide').addEventListener('click',resetProject);
    $('projectSearch').addEventListener('input',event=>{state.search=event.target.value.trim();renderProjects()});
    $('fileSelect').addEventListener('change',event=>showPreview(event.target.value));
    $('refreshPreview').addEventListener('click',()=>{const frame=$('previewFrame');if(!frame.classList.contains('hidden'))frame.src=frame.src});
    $('openPreview').addEventListener('click',()=>{const src=$('previewFrame').src;if(src)window.open(src,'_blank','noopener')});
    $('studioButton').addEventListener('click',async()=>{const button=$('studioButton');button.disabled=true;try{await host('studio',{projectId:state.selected||undefined});toast(state.selected?'Proyecto abierto en OpenDesign Studio.':'OpenDesign Studio abierto.');await loadStatus()}catch(error){toast(error.message,true)}finally{button.disabled=false}});
    $('syncButton').addEventListener('click',async()=>{const button=$('syncButton');button.disabled=true;button.textContent='Conectando';try{const result=await api('/api/integration/sync',{method:'POST',body:'{}'});state.status.integration=result;setStatus(state.status);toast(result.connected?'Studio conectado a OpenClaw.':result.error||'Conexión pendiente.',!result.connected)}catch(error){toast(error.message,true)}finally{button.disabled=false;button.textContent='Sincronizar'}});
    $('previewToggle').addEventListener('click',()=>$('previewPanel').classList.add('open'));$('closePreview').addEventListener('click',()=>$('previewPanel').classList.remove('open'));$('mobileProjects').addEventListener('click',()=>$('sidebar').classList.toggle('open'));
    function readStoredTheme(){try{return localStorage.getItem('lumina-design-theme')||'light'}catch{return'light'}}function writeStoredTheme(theme){try{localStorage.setItem('lumina-design-theme',theme)}catch{}}
    $('themeButton').addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;writeStoredTheme(next)});document.documentElement.dataset.theme=readStoredTheme();
    Promise.all([loadStatus(),loadCatalog(),loadProjects()]).catch(error=>toast(error.message,true));setInterval(loadStatus,15000);
  </script>
</body>
</html>`;
}
